# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Nothing Haunts Us Like the Things We Didn’t Buy
email:            dongjo.ad@gmail.com
description:      How to shop for define your personal style and the soul
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'http://www.nothinghauntsus.com' # The base hostname & protocol for your site
github_username:  
twitter_username: 

markdown:  kramdown

plugins:
  - jekyll-paginate

permalink: pretty
paginate:  24
sass:
  style: compressed

include:
  - _pages

exclude:
  - vendor
  - Gemfile.lock

collections:
  tags:
    output: true
    permalink: /tags/:name/

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             
    bio:              
    gravatar:         
    email:            
    website:          
    github_username:  
    twitter_username: 